guest_list = ["eli", "will", "asher", "paxon"]
print("Hello " + guest_list[0] + ", you are invited to dinner.")
print("Hello " + guest_list[1] + ", you are invited to dinner.")
print("Hello " + guest_list[2] + ", you are invited to dinner.")
print("Hello " + guest_list[3] + ", you are invited to dinner.")
cant_come = guest_list.pop(2)
print("\nUnfortunately, " + cant_come.title() + " can't make it to dinner.")
guest_list.insert(2, "regina")
print("\nHello " + guest_list[2] + ", you are invited to dinner.")
found_table = "I found a bigger dinner table!"
print("\n" + found_table + "\n")
guest_list.insert(0, "michael")
guest_list.insert(2, "sophia")
guest_list.append("daniel")
print("Hello " + guest_list[0] + ", you are invited to dinner.")
print("Hello " + guest_list[1] + ", you are invited to dinner.")
print("Hello " + guest_list[2] + ", you are invited to dinner.")
print("Hello " + guest_list[3] + ", you are invited to dinner.")
print("Hello " + guest_list[4] + ", you are invited to dinner.")
print("Hello " + guest_list[5] + ", you are invited to dinner.")
print("\nSorry, I can only invite two people for dinner.\n")
removed_guest = guest_list.pop()
print("Sorry " + removed_guest.title() + ", I can't invite you to dinner.")
removed_guest = guest_list.pop()
print("Sorry " + removed_guest.title() + ", I can't invite you to dinner.")
removed_guest = guest_list.pop()
print("Sorry " + removed_guest.title() + ", I can't invite you to dinner.")
removed_guest = guest_list.pop()
print("Sorry " + removed_guest.title() + ", I can't invite you to dinner.")
print("\nHello " + guest_list[0] + ", you are still invited to dinner.")
print("Hello " + guest_list[1] + ", you are still invited to dinner.")
del guest_list[1]
del guest_list[0]
